### ISSUE TITLE
[FEATURE]  Live Preview-ს დინამიკური ლინკები env-ის მიხედვით

### ISSUE THREAD

**Issue by CondensedMilk7** [educata/iswavle#73]
#71-ის შემდეგ:

Production-ზე გამოვიყენებთ GitHub Page-ზე დაჰოსტილი ნიმუშიების ბმულებს, თუმცა დეველოპმენტის პროცესში აჯობებს, რომ კოდის ფაილის ბმულები ლოკალური asset-ებიდან გამოვიყენოთ.

ამისთვის დაგვჭირდება Environment ტოკენის შექმნა.

**Comment by KostaD02** [comment]
დაემატა #84
