### ISSUE TITLE
[FEATURE]  სისტემაზე მორგებული თემა

### ISSUE THREAD

**Issue by CondensedMilk7** [educata/iswavle#90]
თანამედროვე აპლიკაციებში ფერების თემის ასარჩევი სამი ვარიანტია:

- ნათელი
- მუქი
- სისტემა

ეს უკანასკნელი გულისხმობს იმ რეჟიმს, რომელიც უკვე ოპერატიულ სისტემაზეა დაყენებული.
UX-ს ოდნავ გავაუმჯობესებთ თუ პირვალნდელი რეჟიმი სისტემის თემას დაემთხვევა.

შეგვიძლია გამოვიყენოთ (ოღონდ რეაქტიულად RxJS-ში):

```js
window.matchMedia('(prefers-color-scheme: dark)');
```

შეგვიძლია პრეფერენსს გამუდმებით ვუსმინოთ ისეთი მომხმარებლებისთის,
რომლებსაც თემა დროის მიხედვით ეცვლებათ (მაგ. დღისით ნათელი, ღამით მუქი).
თუ ეს გადართვა სისტემაში მაშინ მოხდა, როცა აპლიკაციაა გახსნილი, ჩვენი აპლიკაციაც ირეაგირებს.

**Comment by KostaD02** [comment]
დაემატა #94
